from noveltychecker.utils.model_client import get_llm_client
import os
import asyncio
import pandas as pd
from tqdm import tqdm


def parser(output_text):
    stylelised_idea = (
        output_text.split("<Stylised Idea>")[-1].split("</Stylised Idea>")[0].strip()
    )
    return stylelised_idea


async def run_stylechange(idea):
    incontext_examples = """
    - Create a benchmarking approach designed to evaluate analogical reasoning in language models by utilizing a novel analogical reasoning corpus aggregated through environmental dna metabarcoding techniques applied to text data. This corpus would be constructed by identifying and extracting analogical expressions from a vast array of textual sources, similar to how eDNA captures biodiversity. The agent will be evaluated through performance comparison with existing datasets to measure its ability to identify and reason with analogies.
    - Develop a mobile application that allows users to interactively provide feedback on outputs generated by language models. This application would feature intuitive interfaces for users to annotate and edit generated content directly on their devices. The feedback gathered will be processed in real-time to align language models with user preferences without the need for extensive fine-tuning. The effectiveness of this approach will be evaluated using a simulated user evaluation where a GPT-4 model simulates diverse user interactions and preferences. This approach leverages the ease of mobile input to continuously update and refine the model's understanding of user preferences.
    - Create an advanced literature search tool that uses citation-based suggestions with visualizations to boost scientific innovation. The tool would provide interactive visualizations of citation networks combined with detailed author profiles, allowing users to explore how different researchers and their work interconnect. Users could refine their searches using keywords and see the influence of various authors across different domains. The effectiveness of this tool would be assessed through simulated sessions and user study, ensuring it supports researchers in identifying novel connections and fostering interdisciplinary innovation.
    - Develop a visual toolkit with graphical interface designed to review genetic algorithms in bioinformatics tools. This toolkit will enable researchers to visually explore and compare different genetic algorithms in various bioinformatics applications such as gene therapy, microbial genome analysis, and biotechnology. The system will support in-lab and interview studies, allowing users to provide feedback and iteratively refine the tool based on hands-on experiences and expert insights.
    - Develop a hybrid framework that combines sample-wise protective noise in images with techniques from topology-based adversarial training to simultaneously protect datasets from unauthorized exploitation and enhance the robustness of neural networks. Specifically, the framework would generate imperceptible noise for image datasets that not only renders the data unlearnable to unauthorized users but also incorporates topology alignment principles to maintain the integrity of the model's feature space against adversarial attacks. For instance, a real-world use case could involve protecting sensitive medical imaging data from unauthorized training while ensuring the trained model resists adversarial manipulations targeting diagnosis outputs. The framework would be evaluated by conducting benchmark dataset experiments, such as CIFAR and ImageNet, to measure both the protective efficacy of the noise and the robustness against state-of-the-art adversarial attacks (e.g., PGD-attack). This dual-purpose approach provides a comprehensive solution to data privacy and model reliability challenges in machine learning systems.
    - To address increasing privacy concerns in diffusion models, this research proposes incorporating a backdoor detection framework to analyze training datasets for unauthorized usage. The framework would identify anomalies or patterns suggesting that protected images have been exploited during model fine-tuning or training. By using tailored metrics derived from the generative performance of diffusion models, the framework can flag discrepancies in the quality or style of images safeguarded against unauthorized use as a proxy for unauthorized learning attempts. The system would utilize both static quality checks and dynamic model behavior analysis to detect exploitation. Validation of this framework would involve a controlled setup where diffusion models are trained on datasets with embedded protective signals. Success metrics would be determined by the framework’s ability to consistently detect unauthorized training, as well as its impact on downstream generative quality. Quality assessment of generated images would evaluate whether flagged models produce outputs distinct from legal or authorized models, ensuring that legitimate generative tasks remain unaffected. This dual-layer defense would strengthen the existing unlearnable data mechanisms and provide an actionable detection approach for monitoring diffusion model usage.
    - To create believable human behavior simulations, this study would employ graph reinforcement learning techniques with graph neural networks (GNNs) to model intricate decision-making in urban traffic scenarios. The method would construct a graph-based representation of urban traffic, where the nodes represent human drivers or pedestrians, and the edges encapsulate their interactions and dependencies. The GNN would extract contextual features such as spatial proximity, intent prediction, and decision-making tendencies. These features would be processed through graph reinforcement learning to inform the agents' behavior dynamically. The result is a system where agents demonstrate human-like decision-making, such as yielding, aggressive driving, or cautious pedestrian walking, in response to diverse traffic scenarios. The simulation-based comparative analysis would evaluate the approach by comparing its output with real-world traffic patterns, focusing on metrics like realism, decision-making accuracy, and emergent behaviors. This approach could be instrumental in designing traffic systems and autonomous vehicles that better coexist with human drivers, ultimately reducing accidents and improving traffic flow.
    - Introduce a collaborative system where emotion-expressing conversational agents assist interdisciplinary teams to enable interdisciplinary scientific research. These agents would participate in team discussions, providing emotionally intelligent feedback and suggestions tailored to the team's dynamics and the project's needs. For example, during a virtual lab meeting, an agent could express concern if a member seems frustrated or provide motivational encouragement to foster collaboration. By integrating these agents into the workflow, researchers could improve communication and idea generation, especially in emotionally charged or sensitive research areas like medical ethics or environmental crises. The system's effectiveness would be validated through experimental validation of scientific outputs, such as comparing the outcomes of research teams using emotion-aware agents to those using traditional tools. This framework could revolutionize collaborative research by combining technical problem-solving with emotional intelligence.
    """
    prompt = [
        {
            "role": "system",
            "content": (
                "You are an intelligent assistant that paraphrases the provided idea (between <IDEA> and </IDEA>) in a particular style. "
            ),
        },
        {
            "role": "user",
            "content": f"""Here are some examples of the style I want the idea to be rewritten in:

            {incontext_examples}
            """,
        },
        {
            "role": "user",
            "content": (
                "When rewriting the idea, ensure that you adapt the style to contain a purpose (which clearly has the overall goal of the idea), "
                "mechanism (a process or approach), and evaluation (how the mechanism and purpose can be evaluated). Please don't write purpose, mechanism, and evaluation separately, "
                "instead just improve the style of the idea.\n\n"
                "Make sure to follow the length of the examples provided (200-300 words)."
                "The goal is to still be able to retreive the same literature with the idea and its stylised version."
            ),
        },
        {"role": "assistant", "content": "Sure, please provide the IDEA."},
        {"role": "user", "content": idea},
        {
            "role": "user",
            "content": "Provide it between <Stylised Idea> and </Stylised Idea> tags.",
        },
    ]

    client = get_llm_client(os.getenv("STYLE_CHANGE_MODEL", "o3-mini"))
    output_text, _ = await client.a_chat(
        model=os.getenv("STYLE_CHANGE_MODEL", "o3-mini"),
        messages=prompt,
    )
    print("idea: ", idea)
    print("output: ", output_text)
    stylelised_idea = parser(output_text)
    print("style: ", stylelised_idea)
    return stylelised_idea


if __name__ == "__main__":

    title = "Evaluating Action Tracking in ReAct Agents for Text-Based Game Navigation"
    abstract = "This paper presents an experimental evaluation of action tracking mechanisms in ReAct (Reasoning and Acting) agents within text-based game environments. We compare three agent variants: a random baseline, a standard ReAct implementation, and a ReAct agent augmented with action history tracking. Using TextWorldExpress's CookingWorld environment, we evaluate these agents across 50 episodes, measuring task completion rates and average scores. Our results show that while both ReAct variants significantly outperform the random baseline, the addition of action tracking does not provide statistically significant improvements over the standard ReAct implementation."
    idea = f"Title: {title} Abstract: {abstract}"
    styleised_idea = asyncio.run(run_stylechange(idea))
    print(styleised_idea)
